export const seatLayouts = {
  "6-max": [
    { id: "seat_0_hero", x: 47, y: 73.8, anchor: "center", cardDock: "top" },
    { id: "seat_1_left_lower", x: 11.7, y: 36.8, anchor: "center", cardDock: "right" },
    { id: "seat_2_left_upper", x: 11.7, y: 60.2, anchor: "center", cardDock: "right" },
    { id: "seat_3_top", x: 47, y: 13.5, anchor: "center", cardDock: "bottom" },
    { id: "seat_4_right_lower", x: 88.3, y: 36.8, anchor: "center", cardDock: "left" },
    { id: "seat_5_right_upper", x: 88.3, y: 60.2, anchor: "center", cardDock: "left" },
  ],
  "8-max": [
    { id: "seat_0_hero", x: 46.6, y: 74.8, anchor: "center", cardDock: "top" },
    { id: "seat_1_bottom_right", x: 76.8, y: 70.3, anchor: "center", cardDock: "top" },
    { id: "seat_2_right_mid", x: 84.1, y: 40.6, anchor: "center", cardDock: "left" },
    { id: "seat_3_right_upper", x: 76.8, y: 14.2, anchor: "center", cardDock: "left" },
    { id: "seat_4_top_right", x: 46.6, y: 11.5, anchor: "center", cardDock: "bottom" },
    { id: "seat_5_top_left", x: 29.6, y: 11.5, anchor: "center", cardDock: "bottom" },
    { id: "seat_6_left_upper", x: 23.2, y: 14.2, anchor: "center", cardDock: "right" },
    { id: "seat_7_left_mid", x: 15.2, y: 40.6, anchor: "center", cardDock: "right" },
  ],
  "9-max": [
    { id: "seat_0_hero", x: 46.6, y: 74.8, anchor: "center", cardDock: "top" },
    { id: "seat_1_bottom_right", x: 72.6, y: 77.3, anchor: "center", cardDock: "top" },
    { id: "seat_2_right_mid", x: 84.1, y: 50.6, anchor: "center", cardDock: "left" },
    { id: "seat_3_right_upper", x: 84.1, y: 25.2, anchor: "center", cardDock: "left" },
    { id: "seat_4_top_right", x: 60.6, y: 11.5, anchor: "center", cardDock: "bottom" },
    { id: "seat_5_top_left", x: 29.6, y: 11.5, anchor: "center", cardDock: "bottom" },
    { id: "seat_6_left_upper", x: 15.9, y: 25.2, anchor: "center", cardDock: "right" },
    { id: "seat_7_left_mid", x: 15.9, y: 50.6, anchor: "center", cardDock: "right" },
    { id: "seat_8_bottom_left", x: 27.4, y: 77.3, anchor: "center", cardDock: "top" },
  ],
};
