export const seatLayouts = {
  "6-max": [
    { id: "seat_0_hero", x: 47, y: 73.8, anchor: "center", cardDock: "top" },
    { id: "seat_1_left_lower", x: 5.7, y: 26.8, anchor: "center", cardDock: "top" },
    { id: "seat_2_left_upper", x: 5.7, y: 60.2, anchor: "center", cardDock: "top" },
    { id: "seat_3_top", x: 47, y: 13.5, anchor: "center", cardDock: "top" },
    { id: "seat_4_right_lower", x: 84.3, y: 26.8, anchor: "center", cardDock: "top" },
    { id: "seat_5_right_upper", x: 84.3, y: 60.2, anchor: "center", cardDock: "top" },
  ],
  "8-max": [
    { id: "seat_0_hero", x: 46.6, y: 74.8, anchor: "center", cardDock: "top" },
    { id: "seat_1_bottom_right", x: 78.6, y: 70.3, anchor: "center", cardDock: "top" },
    { id: "seat_2_right_mid", x: 84.1, y: 40.6, anchor: "center", cardDock: "top" },
    { id: "seat_3_right_upper", x: 78.6, y: 14.2, anchor: "center", cardDock: "top" },
    { id: "seat_4_top_right", x: 46.6, y: 10.5, anchor: "center", cardDock: "top" },
    { id: "seat_6_left_upper", x: 14.4, y: 14.2, anchor: "center", cardDock: "top" },
    { id: "seat_7_left_mid", x: 5.2, y: 40.6, anchor: "center", cardDock: "top" },
    { id: "seat_8_bottom_left", x: 14.4, y: 70.3, anchor: "center", cardDock: "top" },
  ],
  "9-max": [
    { id: "seat_0_hero", x: 46.6, y: 74.8, anchor: "center", cardDock: "top" },
    { id: "seat_1_bottom_right", x: 72.6, y: 77.3, anchor: "center", cardDock: "top" },
    { id: "seat_2_right_mid", x: 84.1, y: 50.6, anchor: "center", cardDock: "top" },
    { id: "seat_3_right_upper", x: 84.1, y: 25.2, anchor: "center", cardDock: "top" },
    { id: "seat_4_top_right", x: 60.6, y: 11.5, anchor: "center", cardDock: "top-inset" },
    { id: "seat_5_top_left", x: 29.6, y: 11.5, anchor: "center", cardDock: "top-inset" },
    { id: "seat_6_left_upper", x: 5.2, y: 25.2, anchor: "center", cardDock: "top" },
    { id: "seat_7_left_mid", x: 5.2, y: 50.6, anchor: "center", cardDock: "top" },
    { id: "seat_8_bottom_left", x: 22.4, y: 77.3, anchor: "center", cardDock: "top" },
  ],
};
